### PR TITLE
Zotero Integration

### PR DESCRIPTION
**Pull request by bnavetta**
This adds integration with Zotero and the Better BibTeX extension, based on [bnavetta/vscode-zotero-latex](https://github.com/bnavetta/vscode-zotero-latex), as discussed in bnavetta/vscode-zotero-latex#3.

It works pretty much the same way - there's a command for adding a citation from Zotero and a command for opening a citation in Zotero based on the cite key.

### CODE REVIEW

**Comment by tecosaur** [comment]
This is great, thanks! I'll try to get round to testing it soon :smiley:

**Comment by tecosaur** [comment]
Ok. Generally looks good, two issues I've come across though:
 - Open in Zotero doesn't seem to do anything. Debugging suggests it's an issue with the final uri/BBT
 - If the zotero server is not running, this silently fails/hangs — no error is given
 - The vscode cite method doesn't seem to work (see gif below)

zotero-c-not-work

Log message
```
[02:00:28] Searching Zotero for 'e'
[02:00:28] Got 5 search results from Zotero
[02:00:30] Added citation: \autocite{}
```

If you can resolve those issues I think I'll be happy to merge.

**Comment by tecosaur** [comment]
I think if there are no items selected and someone presses enter it's fair to say that they want to pick that one. To me that would be a good addition.

With "open in zotero", for me the url is `zotero://select/items/bbt%3AbringhurstElementsTypographicStyle2004`

Interestingly on a command line I get this (I'm on linux):
```
╰> xdg-open zotero://select/items/bbt%3AbringhurstElementsTypographicStyle2004
gio: zotero://select/items/bbt%3AbringhurstElementsTypographicStyle2004: The specified location is not supported
```

**Comment by bnavetta** [comment]
Sounds good. Seems like using active items still requires them to arrow down to highlight something, but I think it's a reasonable middle ground.

**Comment by tecosaur** [comment]
Nice! One little thing, would it be easy to add a quick test to check that Zotero is started/open and warn if it isn't?

**Comment by tecosaur** [comment]
I'm now happy :smiley:

**Pull request merged**
