### PR TITLE
Remove dependency on workshop

### PR DESCRIPTION
**Pull request by leoleoasd**
Gradually remove dependency on workshop since they are no longer interested in maintaining support for this repo (James-Yu/LaTeX-Workshop#3057).
Tasks:

- [x] Manager
- [x] getGraphicsPath
- [x] completer.command.usedPackages
- [ ] ~~viewer~~ (Won't fix for now)

Support of tikz live preview seems a lot of work, maybe I'll refactor the current implementation.

### CODE REVIEW

**Comment by tecosaur** [comment]
Feel free to merge this whenever you feel comfortable doing so. Just poke me when you think a release is in order.

**Comment by tecosaur** [comment]
Cool, no pressure. I just wanted to make sure you weren't waiting for a review from me. I'd love to, but quite I simply don't have the time and so I'm just trusting you 🙂.

**Comment by leoleoasd** [comment]
Finally got some spare time after my crazy junior year. All functions should be working now (except for Tikz preview, I'm considering removing this feature?). I noticed that pasting images from WSL remote isn't working. I tried to fix that but I'm waiting for the reply from PowerShell developers (See Powershell/PowerShell#17623). After that, I think we can finally release this!

**Comment by asteppke** [comment]
@leoleoasd: Thank you, that's great news! The TikZ preview might not be essential but as other previewers (TikZedt ...) are not working well this would be sad to drop. Even the most basic support would be useful.

**Comment by leoleoasd** [comment]
Things needed from Workshop side are PDF viewers. Using existing code from Workshop requires lots of work (they implemented things like synctex, which we don't require), I'll try to find another way to preview rendered pdf after other functions are merged and released.

**Comment by leoleoasd** [comment]
Sent an email to @tecosaur to discuss the publish process. I'm pinging here since my last email serval month ago goes into the junk box.

**Comment by tecosaur** [comment]
Got your email :slightly_smiling_face: and glad for the ping too (I seem to loose the odd email on busy days...). I'll get back to you on publishing in a few hours.

**Comment by leoleoasd** [comment]
Just to remind @tecosaur, I haven't received the email yet.

**Comment by tecosaur** [comment]
Ah yep :sweat_smile: I was overly ambitious on Thursday and forgot how busy I was. I should have said, "I'll get back to you on the weekend".

**Pull request merged**
