### PR TITLE
Fixes to make sure that everything works fine with reverted commit from LaTeX-Workshop.

### LINKED ISSUE #347: New maintainer?
LaTeX-workshop dropped support for this extension (see James-Yu/LaTeX-Workshop#3009). Maybe we should mark this extension unuseable, or remove it from vscode extension marketplace.

### PR DESCRIPTION
**Pull request by leoleoasd**
This PR contains fixes to make sure that everything works fine with leoleoasd/LaTeX-Workshop@ea05a444e0e6a63d4b29d61b9d531f4905d2b0c7.

I'm volunteering myself to continue to maintain this repo. I've made some changes, and after everything works fine I'll contact people from LaTeX-Workshop to re-add support for this project.

I've sent an email to you (`tec#tecosaur.com`) to answer some of your concerns from #347.

todo list:
- [x] Formatted paste
- [x] Zotero support
- [x] Live Snippets
- [x] Tikx picture live preview
- [x] Remove word count command but keep it in status bar (LaTeX-Worhshop already has this)

closes #347

### CODE REVIEW

**Comment by tecosaur** [comment]
Hi Leo, thanks for the PR. I notice a `console.log()` that looks like it may be accidental, but other than that this looks good.

You've also prompted me to look at my emails, looks like you ended up in my spam folder :( that should be resolved now though.

**Comment by leoleoasd** [comment]
The `tsc` compiler complains about `got` a lot, and I'm not familiar with it. I've replaced it with `axios` which I am more familiar to. I verified that Zotero integration works like a charm.

As for tikz picture previewing, the command `viewtikzpicture` complains that `range`(see [this line](https://github.com/leoleoasd/LaTeX-Utilities/blob/dev/src/main.ts#L36)) is undefined. Clicking `view tikz picture` which is shown above `\begin{tikzpicture` gave the following error:
```
Cannot read property '/VAR/FOLDERS/27/YM8Q81CJ3K7GMJ317J3R7SF00000GN/T/VSCODE-LATEXUTILS/TIKZPREVIEW-EXP-REPORT-DX37XY/TIKZPICTURE-41092352.PDF' of undefined
```

Still investigating.

**Comment by leoleoasd** [comment]
Clicking `view TikZ picture` is working now 🎉

@tecosaur Does manually invoke the `viewtikzpicture` command used to work, or it is only intended to be invoked at clicking the `view TikZ picture` prompt? It seems that the callback for `registerCommand` in vscode api has no parameters.

**Comment by leoleoasd** [comment]
It seems that the parameters are passed in [CodeLens](https://github.com/leoleoasd/LaTeX-Utilities/blob/dev/src/providers/tikzcodelense.ts#L15-L20). Should we give a prompt to tell uses that manually invoking the preview command isn't supported?

**Comment by tecosaur** [comment]
That could make sense. The only intended use is clicking the "View TikZ picture" code lens.

**Comment by leoleoasd** [comment]
Sadly, people from the Workshop refused to add support. I'm moving the necessary code from the Workshop to provide these features, but this takes time.
The Workshop is licensed under MIT, so using their code seems fine.

**Comment by tecosaur** [comment]
@leoleoasd have you approached the LaTeXWorkshop team about the prospect of adding support back?

**Comment by leoleoasd** [comment]
@tecosaur see James-Yu/LaTeX-Workshop#3057

**Comment by tecosaur** [comment]
Thanks for the link.

Huh, that's a bit of a pain. I'm not sure what the "maintenance burden" in just exposing a few functions is, but at the end of the day it is their call.

**Comment by leoleoasd** [comment]
I'm fine with "maintenance burden", for example, we do use some of their features marked `@deprecated`. Though I think this can be overcome, for example, I've changed the exposed function on their side to use the new API. However, they still believe that support should not be added.

I'm working on moving the necessary code.

**Comment by tecosaur** [comment]
Did you mean to merge this instead of closing it?

**Comment by tecosaur** [comment]
Ah, I take it #349 supersedes this.

**Comment by leoleoasd** [comment]
> Did you mean to merge this instead of closing it?

I've opened a new pr to track the status of removing the dependency.
This branch requires my fork of Workshop, so I think it's better to not merge this into master.

**Pull request closed without merging**
